from BuildConfig import *

Import('env')

testEnv = env.Clone()

pathToRoot = ".."

updateEnv(testEnv, pathToRoot)

Export('testEnv')

# Build all modules within the source directory
for dir in testModules:

    objects = []
    
    # Custom SConscript
    if os.path.exists(join(dir, "SConscript")):
        SConscript(join(dir, "SConscript"))
    else:
        for file in Glob(join(dir, '*.cpp')):
    		fileName = os.path.basename(str(file))
    		
    		fileName = fileName.split(".")[0]
    
    		outDir = join(getBuildPath(pathToRoot), dir, fileName)
    		objects = objects + testEnv.Object(source=file, target=outDir)
	
    	# Example: ../build/test/glm/glm
        testEnv.Program(join(getBuildPath(pathToRoot), testPath, dir, dir), objects)