from BuildConfig import *


Import('env')

testEnv = env.Clone()

pathToRoot = ".."

setupEnv(testEnv, pathToRoot)

# Build all modules within the source directory
for dir in testModules:

    objects = []

    for file in Glob(join(dir, '*.cpp')):
		fileName = os.path.basename(str(file))
		
		fileName = fileName.split(".")[0]
		print fileName

		outDir = join(getBuildPath(pathToRoot), testDir, dir, fileName)
		objects = objects + testEnv.Object(source=file, target=outDir)
	
	# Example: ../build/test/glm/glm
    testEnv.Program(join(getBuildPath(pathToRoot), testDir, dir, dir), objects, LIBS=[])