from BuildConfig import *


Import('testEnv')

texEnv = testEnv.Clone()

pathToRoot = "../.."

setupEnv(texEnv, pathToRoot)

outDir = join(getBuildPath(pathToRoot), testDir, "Field3D")

sources = []
#sources = getSource("texture", pathToRoot)
#sources = sources + getSource("lua", pathToRoot)
#sources = sources + getSource("geom", pathToRoot)
#sources = sources + getSource("util", pathToRoot)
#sources = sources + getSource("core", pathToRoot)

objects = []

for source in sources:
    source = str(source)
    name = (source.split("/")[-1]).split(".")[0]
    objects.append(texEnv.Object(join(outDir, name), source))

field3DObj = texEnv.Object(join(outDir, "UnitTest"), "UnitTest.cpp")

texEnv.Program(join(outDir, "unittest"), objects + [field3DObj])