from BuildConfig import *
import os

Import('testEnv')

f3DEnv = testEnv.Clone()

pathToRoot = "../.."

updateEnv(f3DEnv, pathToRoot)

outDir = join(getBuildPath(pathToRoot), "Field3D")

field3DObj = f3DEnv.Object(join(outDir, "Field3DUnitTest"), "UnitTest.cpp")
    
f3DEnv.Program(join(getBuildPath(), testPath, "Field3D-unittest"), [field3DObj])