from BuildConfig import *


Import('testEnv')

#testEnv = testEnv.Clone()

pathToRoot = "../.."

setupEnv(testEnv, pathToRoot)

outDir = join(getBuildPath(pathToRoot), "texture")

objects = []

objects = objects + buildSource("texture",testEnv, pathToRoot)
objects = objects + buildSource("geom",testEnv, pathToRoot)
objects = objects + buildSource("util",testEnv, pathToRoot)
objects = objects + buildSource("core",testEnv, pathToRoot)
objects = objects + buildSource("light",testEnv, pathToRoot)
objects = objects + buildSource("lua",testEnv, pathToRoot)

exrWriteObj = testEnv.Object(join(outDir, "testExrWrite"), "exrWrite.cpp")
procTestObj = testEnv.Object(join(outDir, "testProcExr"), "procTest.cpp") 

testEnv.Program(join(getBuildPath(pathToRoot), testPath, "EXR-WriteTest"), objects + [exrWriteObj])
testEnv.Program(join(getBuildPath(pathToRoot), testPath,"EXR-ProcTest"), objects + [procTestObj])