from BuildConfig import *


Import('testEnv')

texEnv = testEnv.Clone()

pathToRoot = "../.."

setupEnv(texEnv, pathToRoot)

outDir = join(getBuildPath(pathToRoot), testDir, "texture")

sources = getSource("texture", pathToRoot)
sources = sources + getSource("lua", pathToRoot)
sources = sources + getSource("geom", pathToRoot)
sources = sources + getSource("util", pathToRoot)
sources = sources + getSource("core", pathToRoot)

objects = []

for source in sources:
    source = str(source)
    name = (source.split("/")[-1]).split(".")[0]
    objects.append(texEnv.Object(join(outDir, name), source))

exrWriteObj = texEnv.Object(join(outDir, "exrWrite"), "exrWrite.cpp")
procTestObj = texEnv.Object(join(outDir, "procTest"), "procTest.cpp") 

texEnv.Program(join(outDir, "exrWrite"), objects + [exrWriteObj])
texEnv.Program(join(outDir,"procTest"), objects + [procTestObj])