from BuildConfig import *


Import('env')

testEnv = env.Clone()

pathToRoot = "../.."

setupEnv(testEnv, pathToRoot)

objects = []

# Build library
libFiles = ['luabindTest.cpp']
outDir = join(getBuildPath(pathToRoot), testDir, "luabind")
libObjects = []
libObjects = libObjects + testEnv.SharedObject(outDir, libFiles)
testEnv.SharedLibrary(join(outDir,"luaBindLib"), libObjects)

testEnv.Program(join(outDir,"cppfunc"), "cppfunc.cpp")
testEnv.Program(join(outDir,"cppclass"), "cppclass.cpp")
