from BuildConfig import *


Import('testEnv')

#testEnv = testEnv.Clone()

pathToRoot = "../.."

updateEnv(testEnv, pathToRoot)

outDir = join(getBuildPath(pathToRoot), "luabind")

sources = ["unittests.cpp"]

objects = []

for source in sources:
    source = str(source)
    name = (source.split("/")[-1]).split(".")[0]
    objects.append(testEnv.Object(join(outDir, name), source))

objects = objects + buildSource("geom",testEnv, pathToRoot)
objects = objects + buildSource("util",testEnv, pathToRoot)
objects = objects + buildSource("core",testEnv, pathToRoot)
objects = objects + buildSource("light",testEnv, pathToRoot)
objects = objects + buildSource("lua",testEnv, pathToRoot)

testEnv.Program(join(getBuildPath(pathToRoot),testPath ,"Luabind-unittest"), objects)